# Generated by Django 6.0.2 on 2026-03-03 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='GROQ_API_KEY',
            new_name='groq_api_key',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='JINA_API_KEY',
            new_name='jina_api_key',
        ),
    ]
