[project]
name = "slm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "cryptography>=46.0.5",
    "distilabel>=1.5.3",
    "django>=6.0.2",
    "django-cors-headers>=4.9.0",
    "django-encrypted-model-fields>=0.6.5",
    "djangorestframework>=3.16.1",
    "gradio>=6.6.0",
    "groq>=0.37.1",
    "langchain-community>=0.4.1",
    "langchain-core>=1.2.16",
    "langchain-groq>=1.1.2",
    "langchain-text-splitters>=1.1.1",
    "markdown>=3.10.2",
    "poethepoet>=0.42.1",
    "psycopg[binary]>=3.3.3",
    "pydantic>=2.12.5",
    "pygments>=2.19.2",
    "python-dotenv>=1.2.1",
    "pyyaml>=6.0.3",
    "requests>=2.32.5",
    "rich>=14.3.3",
    "unstructured>=0.21.5",
]

[tool.poe.tasks]
frontend = {cmd = "npm run dev", cwd = "frontend"}
backend = {cmd = "uv run manage.py runserver", cwd = "slm_finetune"}
dev = {parallel = ["frontend", "backend"]}