# Generated by Django 6.0.2 on 2026-03-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('scrape_type', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=255)),
                ('number_of_links_scrapped', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('udpated_at', models.DateTimeField(auto_now=True)),
                ('files', models.FileField(upload_to='', verbose_name='documents/')),
                ('message', models.TextField()),
            ],
        ),
    ]
