web_scrapping:
  url: "https://www.mindmapdigital.ai/"
  api_key: ${JINA_API_KEY}
  scrape_type: "deep" ## flash or deep
  remove_temp_files: True

ProcessMarkdownQAPairs:
  api_key: ${GROQ_API_KEY}
  model_id: "qwen/qwen3-32b"
  file_path: "/home/mindmap/Desktop/SLM/unstructured_data/cleaned_output.md"